QUESTION 1   
Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [255]:
import selenium
from selenium import webdriver
import time
import pandas as pd
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')

QUESTION 2
Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time

In [9]:
driver.get("https://www.bcci.tv/")

In [30]:
button=driver.find_element(By.XPATH,"/html/body/nav/div[1]/button")
button.click()

In [32]:
international=driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
international.click()

In [34]:
match_title=[]
series=[]
place=[]
date=[]
matchtime=[]          
datetime=[]

for i in driver.find_elements(By.XPATH,"//span[@class='matchOrderText ng-binding ng-scope']"):
    match_title.append(i.text)
    
for i in driver.find_elements(By.XPATH,"//span[@class='ng-binding']"):
    series.append(i.text)

for i in driver.find_elements(By.XPATH,"//span[@class='ng-binding ng-scope']"):
    place.append(i.text)
    
for i in driver.find_elements(By.XPATH,"//div[@class='match-top-info d-flex align-items-center justify-content-between']"):
    datetime.append(i.text.replace('\n',' '))
    
date=[i.split(' ',3)[:3] for i in datetime]
date=[' '.join(i) for i in date]
matchtime=[i.split(' ',3)[-1] for i in datetime]

matches_data=pd.DataFrame({'Match Title': match_title,
                          "Series": series,
                          "Place": place,
                          "Date": date,
                          "Time": matchtime})
matches_data

,Match Title,Series,Place,Date,Time
0,4th T20I -,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,"Steyn City School Ground,",2 JAN 2023,5:15 PM IST
1,1st T20I -,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Wankhede Stadium,",3 JAN 2023,7:00 PM IST
2,5th T20I -,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,"Steyn City School Ground,",4 JAN 2023,1:30 PM IST
3,2nd T20I -,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Maharashtra Cricket Association Stadium,",5 JAN 2023,7:00 PM IST
4,3rd T20I -,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Saurashtra Cricket Association Stadium,",7 JAN 2023,7:00 PM IST
5,1st ODI -,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Barsapara Cricket Stadium,",10 JAN 2023,1:30 PM IST
6,2nd ODI -,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Eden Gardens,",12 JAN 2023,1:30 PM IST
7,3rd ODI -,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Greenfield International Stadium,",15 JAN 2023,1:30 PM IST

QUESTION 4
Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)

In [68]:
url="http://statisticstimes.com/"
driver.get(url)

In [74]:
economy=driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/button")
economy.click()

In [83]:
india=driver.find_element(By.XPATH,"//div[@class='navbar']/div[2]/div/a[3]").get_attribute("href")
print(india)
driver.get(india)

https://www.statisticstimes.com/economy/india-statistics.php

In [84]:
GDP_of_indian_states=driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").get_attribute("href")
print(GDP_of_indian_states)
driver.get(GDP_of_indian_states)

https://www.statisticstimes.com/economy/india/indian-states-gdp.php

In [85]:
driver.execute_script("window.scrollTo(0,1000)")

In [87]:
ranks=[]
states=[]
GSDP_18_19=[]
GSDP_19_20=[]
share_18_19=[]
GDP_in_billion=[]

for rank in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[1]"):
    ranks.append(rank.text)

for state in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[2]"):
    states.append(state.text)
9
for gsdp in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[4]"):
    GSDP_18_19.append(gsdp.text)  

for gsdp in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[3]"):
    GSDP_19_20.append(gsdp.text)    
    
for share in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[5]"):
    share_18_19.append(share.text)    

for gdp in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[6]"):
    GDP_in_billion.append(gdp.text)
       
print(ranks[0:2])
print(states[0:2])
print(GSDP_18_19[0:2])
print(GSDP_19_20[0:2])
print(share_18_19[0:2])
print(GDP_in_billion[0:2])

['1', '2']
['Maharashtra', 'Tamil Nadu']
['2,632,792', '1,630,208']
['-', '1,845,853']
['13.94%', '8.63%']
['399.921', '247.629']

In [88]:
print(len(ranks))
print(len(states))
print(len(GSDP_18_19))
print(len(GSDP_19_20))
print(len(share_18_19))
print(len(GDP_in_billion))

33
33
33
33
33
33

In [89]:
df=pd.DataFrame({})
df["Rank"]=ranks
df["State"]=states
df["GSDP(19-20)"]=GSDP_19_20
df["GSDP(18-19)"]=GSDP_18_19
df["Share(18-19)"]=share_18_19
df["GDP($ billion)"]=GDP_in_billion
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

QUESTION 5
Scrape the details of trending repositories on Github.com. Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [90]:
driver=webdriver.Chrome(r"C://Chromedriver.exe")
url="https://github.com/"
driver.get(url)

In [92]:
dropmenu=driver.find_element(By.XPATH,"//button[@class='js-details-target Button--link Button--medium Button d-lg-none color-fg-inherit p-1']")
dropmenu.click()

In [93]:
opensource=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
opensource.click()

In [94]:
trending=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a").get_attribute("href") 
print(trending)
driver.get(trending)

https://github.com/trending

In [95]:
repository_title=[]
repository_description=[]
contributors_count=[]
language_used=[]

In [97]:
for title in driver.find_elements(By.XPATH,"//article[@class='Box-row']/h1/a"):
    repository_title.append(title.text)
print(repository_title[0:3])

['Z4nzu / hackingtool', 'karpathy / nanoGPT', 'neonbjb / tortoise-tts']

In [98]:
URL_list=[]
for url in driver.find_elements(By.XPATH,"//article[@class='Box-row']/h1/a"):
    URL_list.append(url.get_attribute("href"))
URL_list[0:3]

['https://github.com/Z4nzu/hackingtool',
 'https://github.com/karpathy/nanoGPT',
 'https://github.com/neonbjb/tortoise-tts']

In [131]:
for i in URL_list:
    driver.get(i)
    
    try:
        description=driver.find_element(By.XPATH,"//div[@class='BorderGrid-cell']/p")
        repository_description.append(description.text)
    except NoSuchElementException as e:
        repository_description.append("---")
     
    try:
        count=driver.find_element(By.XPATH,"//span[@class='Counter']")
        contributors_count.append(count.text.split(" "))
    except NoSuchElementException as e:
        contributors_count.append("---")
    #language used
    try:
        lang=driver.find_element(By.XPATH,"//div[@class='BorderGrid-cell']")
        language_used.append(lang.text.replace("\n"," "))
    except NoSuchElementException as e:
        language_used.append("---")
        
print(repository_description[0:2])
print(contributors_count[0:2])
print(language_used[0:2])

['ALL IN ONE Hacking Tool For Hackers', 'The simplest, fastest repository for training/finetuning medium-sized GPTs.']
['---', '---']
['---', '---']

In [130]:
print(len(repository_title))
print(len(repository_description))
print(len(contributors_count))
print(len(language_used))

25
152
150
150

In [120]:
df=pd.DataFrame({})
df["Repository title"]=repository_title[:25]
df["Repository description"]=repository_description[:25]
df["Contributors count"]=contributors_count[:25]
df["Language used"]=language_used[:25]
df

,Repository title,Repository description,Contributors count,Language used
0,Z4nzu / hackingtool,ALL IN ONE Hacking Tool For Hackers,---,---
1,karpathy / nanoGPT,"The simplest, fastest repository for training/...",---,---
2,neonbjb / tortoise-tts,A multi-voice TTS system trained with an empha...,---,---
3,papers-we-love / papers-we-love,Papers from the computer science community to ...,---,---
4,mouredev / retos-programacion-2023,Ejercicios de código semanales en 2023 de la c...,---,---
5,bigscience-workshop / petals,"🌸 Run 100B+ language models at home, BitTorren...",---,---
6,rmcelreath / stat_rethinking_2023,Statistical Rethinking Course for Jan-Mar 2023,---,---
7,Asabeneh / 30-Days-Of-React,30 Days of React challenge is a step by step g...,---,---
8,gluon-framework / gluon,"A framework for creating ""desktop apps"" from w...",---,---
9,jerryjliu / gpt_index,An index created by GPT to organize external i...,---,---
10,DataTalksClub / data-engineering-zoomcamp,Free Data Engineering course!,---,---
11,godly-devotion / MochiDiffusion,Run Stable Diffusion on Apple Silicon Macs nat...,---,---
12,A-poc / RedTeam-Tools,Tools and Techniques for Red Team / Penetratio...,---,---
13,easychen / stack-roadmap,方糖全栈路线图2023，为「从螺丝钉到一人企业」补全技能栈,---,---
14,vinta / awesome-python,"A curated list of awesome Python frameworks, l...",---,---
15,pola-rs / polars,"Fast multi-threaded, hybrid-streaming DataFram...",---,---
16,mxssl / sre-interview-prep-guide,Site Reliability Engineer Interview Preparatio...,---,---
17,priyankavergadia / GCPSketchnote,If you are looking to become a Google Cloud En...,---,---
18,ashemery / exploitation-course,Offensive Software Exploitation Course,---,---
19,nvm-sh / nvm,Node Version Manager - POSIX-compliant bash sc...,---,---
20,kubernetes / minikube,Run Kubernetes locally,---,---
21,starkoora / wanted-pre-onboarding-challenge-fe...,---,---,---
22,withastro / astro,Build faster websites with Astro's next-gen is...,---,---
23,github / docs,The open-source repo for docs.github.com,---,---
24,airbnb / javascript,JavaScript Style Guide,---,---

QUESTION 6
Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [267]:
driver=webdriver.Chrome(r"C://Chromedriver.exe")
url="https:/www.billboard.com/ "
driver.get(url)

In [270]:
dropmenu=driver.find_element(By.XPATH,"/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button")
dropmenu.click()

In [271]:
charts=driver.find_element(By.XPATH,"//h3[@class='mega-menu-item-heading lrv-u-flex lrv-u-align-items-center lrv-u-color-white u-border-b-2@desktop lrv-u-border-color-brand-primary a-become-color-white-on-expand']")
charts.click()

In [273]:
hot=driver.find_element(By.XPATH,"/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a")
hot.click()

In [275]:
driver.execute_script("window.scrollTo(0,2000)")

In [276]:
Song_Name =[]
Singer=[]
rank=[]
Last_Week=[]
Weeks_on_board=[]

In [220]:
rb=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // lrv-u-background-color-black lrv-u-color-white u-width-100 u-width-55@mobile-max u-width-55@tablet-only lrv-u-height-100p lrv-u-flex lrv-u-flex-direction-column@mobile-max lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey']")
for i in rb:
    if i.text is None :
        rank.append("--") 
    else:
        rank.append(i.text)
print(len(rank),rank)

100 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100']

In [292]:
rank=[]
song_name=[]
artist_name=[]

for i in driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet']"):
    rank.append(i.text.split("\n")[0])

for song in driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']"):
    song_name.append(song.text)

for artist in driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']"):
    artist_name.append(artist.text)
    
print(rank[0:3])
print(song_name[0:3])
print(artist_name[0:3])

['1', '2', '3']
["Rockin' Around The Christmas Tree", 'Jingle Bell Rock', 'Last Christmas']
['Brenda Lee', 'Bobby Helms', 'Wham!']

In [293]:
ranks=[]
for r in driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet']"):
    ranks.append(r.text)
ranks

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100']

In [299]:
ranks=' '.join(ranks).split()
ranks[0:8]

['1', '2', '3', '4', '5', '6', '7', '8']

In [300]:
print(len(ranks))

100

In [307]:
last_week_rank=[]
peak_rank=[]
weeks_on_board=[]

count=0
while count<int(len(ranks)):
    last_week_rank.append(ranks[count])
    peak_rank.append(ranks[count])
    weeks_on_board.append(ranks[count+1])
    count=count+2        
    
print(last_week_rank[0:4])
print(peak_rank[0:4])
print(weeks_on_board[0:4])

['1', '3', '5', '7']
['1', '3', '5', '7']
['2', '4', '6', '8']

In [308]:
print(len(last_week_rank))
print(len(peak_rank))
print(len(weeks_on_board))

50
50
50

In [309]:
print(len(rank))
print(len(song_name))
print(len(artist_name))

100
99
99

QUESTION 7
Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [172]:
import selenium
from selenium import webdriver
import time
import pandas as pd
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')

In [173]:
driver=webdriver.Chrome(r"C://Chromedriver.exe")

In [174]:
URL="https://www.naukri.com/hr-recruiters-consultants"
driver.get(URL)

In [175]:
recruiters=driver.find_element(By.XPATH,"//ul[@class='midSec menu']/li[2]/a").get_attribute("href")
print(recruiters)
driver.get(recruiters)

https://www.naukri.com/recruiters

In [176]:
search_bar=driver.find_element(By.XPATH,"//input[@class='sugInp']")
search_bar.send_keys("Data Science")
search_button=driver.find_element(By.XPATH,"//button[@id='qsbFormBtn']")
search_button.click()

In [177]:
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]
 
for names in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(names.text)

for desg in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(desg.text)

for comp in driver.find_elements(By.XPATH,"//a[2][@class='ellipsis']"):
    Company.append(comp.text)    

for skill in driver.find_elements(By.XPATH,"//div[@class='hireSec highlightable']"):
    Skills.append(skill.text)    
    
print(Name[0:3])
print(Designation[0:3])
print(Company[0:3])
print(Skills[0:3])

['Aakash Harit', 'shravan Kumar Gaddam', 'MARSIAN Technologies LLP']
['HR Manager', 'Company Recruiter', 'Company HR']
['Data Science Network', 'Shore Infotech India Pvt. Ltd', 'MARSIAN Technologies LLP']
['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional', '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software', 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics, Deep Learning, statistics, Data Analytics, Data Analysis, support vector machine']

In [178]:
url_list=[]
for urls in driver.find_elements(By.XPATH,"//p[@class='highlightable']/a[1]"):
    url_list.append(urls.get_attribute("href"))
url_list[0:3]

['https://www.naukri.com/recruiters/aakashharit-1986742?xid=167291252425550000&xp=1',
 'https://www.naukri.com/recruiters/shravankumargaddam-353487?xid=167291252425550000&xp=2',
 'https://www.naukri.com/recruiters/marsiantech?xid=167291252425550000&xp=3']

In [179]:
Location=[]
for i in url_list:
    driver.get(i)
    try:
        loc=driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")
        Location.append(loc.text)
    except NoSuchElementException as e:
        Location.append("---")
print(Location[0:3])

['Delhi', 'Hyderabad / Secunderabad', 'Pune']

In [180]:
print(len(Name))
print(len(Designation))
print(len(Company))
print(len(Skills))
print(len(Location))

50
50
50
50
50

In [181]:
df=pd.DataFrame({})
df["Name"]=Name
df["Designation"]=Designation
df["Company"]=Company
df['Skills they hire for']=Skills
df["Location"]=Location
df

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
34,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",

QUESTION 8
Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [182]:
URL="https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(URL)

In [183]:
driver.execute_script("window.scrollTo(0,2000)")

In [184]:
book_name=[]
author_name=[]
volumes_sold=[]
publisher=[]
genre=[]

for name in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[2]"):
    book_name.append(name.text)

for author in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[3]"):
    author_name.append(author.text)

for volumes in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[4]"):
    volumes_sold.append(volumes.text)

for i in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[5]"):
    publisher.append(i.text)

for i in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[6]"):
    genre.append(i.text)
            
print(book_name[0:2])
print(author_name[0:2])
print(volumes_sold[0:2])
print(publisher[0:2])
print(genre[0:2])

['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows']
['Brown, Dan', 'Rowling, J.K.']
['5,094,805', '4,475,152']
['Transworld', 'Bloomsbury']
['Crime, Thriller & Adventure', "Children's Fiction"]

In [185]:
print(len(book_name))
print(len(author_name))
print(len(volumes_sold))
print(len(publisher))
print(len(genre))

100
100
100
100
100

In [186]:
df=pd.DataFrame({})
df["Book Name"]=book_name
df["Author name"]=author_name
df["Volumes sold"]=volumes_sold
df["Publisher"]=publisher
df["Genre"]=genre
df.style.set_properties(**{'text-align':'left'}).set_table_styles([ dict(selector='th', props=[('text-align', 'left')])])

QUESTION 9
Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:

A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [187]:
URL="https://www.imdb.com/list/ls095964455/"
driver.get(URL)

In [188]:
name=[]
year_span=[]
genre=[]
run_time=[]
ratings=[]
votes=[]

for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/a"):
    name.append(i.text)

for year in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/span[2]"):
    year_span.append(year.text)

for g in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p/span[5]"):
    genre.append(g.text)

for time in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p/span[3]"):
    run_time.append(time.text)

for v in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[4]/span[2]"):
    votes.append(v.text)

for rate in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/div[1]/div/span[2]"):
    ratings.append(rate.text)
    
print(name[0:3])
print(year_span[0:3])
print(genre[0:3])
print(run_time[0:3])
print(ratings[0:3])
print(votes[0:3])

['Game of Thrones', 'Stranger Things', 'The Walking Dead']
['(2011–2019)', '(2016– )', '(2010–2022)']
['Action, Adventure, Drama', 'Drama, Fantasy, Horror', 'Drama, Horror, Thriller']
['57 min', '51 min', '44 min']
['9.2', '8.7', '8.1']
['2,101,772', '1,192,181', '994,934']

In [189]:
print(len(name))
print(len(year_span))
print(len(genre))
print(len(run_time))
print(len(ratings))
print(len(votes))

100
100
100
100
100
100

In [190]:
df=pd.DataFrame({})
df["Name"]=name
df["Year span"]=year_span
df["Genre"]=genre
df["Run time"]=run_time
df["Ratings"]=ratings
df["Votes"]=votes
df.style.set_properties(**{'text-align':'left'}).set_table_styles([ dict(selector='th', props=[('text-align', 'left')])])

QUESTION 10
Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
You have to find the following details:

A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [191]:
URL="https://archive.ics.uci.edu/"
driver.get(URL)

In [192]:
view_all=driver.find_element(By.XPATH,"/html/body/table[1]/tbody/tr/td[2]/span[2]/a").get_attribute("href")
print(view_all)
driver.get(view_all)

https://archive.ics.uci.edu/ml/datasets.php

In [193]:
dataset_name=[]
data_type=[]
task=[]
attribute_type=[]
number_of_attributes=[]
number_of_instances=[]
year=[]

for names in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a"):
    dataset_name.append(names.text)

for dtype in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/p"):
    data_type.append(dtype.text)

for t in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]"):
    task.append(t.text)
    
for attribute in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p"):
    attribute_type.append(attribute.text)

for attribute_count in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]"):
    number_of_attributes.append(attribute_count.text)

for instances in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]"):
    number_of_instances.append(instances.text)

for y in driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]"):
    year.append(y.text)

print(dataset_name[0:3])
print(data_type[0:3])
print(task[0:3])
print(attribute_type[0:3])
print(number_of_attributes[0:3])
print(number_of_instances[0:3])
print(year[0:3])

['Abalone', 'Adult', 'Annealing']
['Data Types', 'Multivariate ', 'Multivariate ']
['Default Task', 'Classification ', 'Classification ']
['Attribute Types', 'Categorical, Integer, Real ', 'Categorical, Integer ']
['# Attributes', '8 ', '14 ']
['# Instances', '4177 ', '48842 ']
['Year', '1995 ', '1996 ']

In [194]:
print(len(dataset_name))
print(len(data_type))
print(len(task))
print(len(attribute_type))
print(len(number_of_attributes))
print(len(number_of_instances))
print(len(year))

622
623
623
623
623
623
623

In [195]:
df=pd.DataFrame({})
df["Dataset Name"]=dataset_name
df["Data Type"]=data_type[1:]
df["Task"]=task[1:]
df["Attribute type"]=attribute_type[1:]
df["No of instances"]=number_of_instances[1:]
df["No of attribute"]=number_of_attributes[1:]
df["Year"]=year[1:]
df.style.set_properties(**{'text-align':'left'}).set_table_styles([ dict(selector='th', props=[('text-align', 'left')])])

QUESTION 1
Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A) Rank B) Name C) Artist D) Upload date E) Views

In [238]:
driver=webdriver.Chrome(r"C://Chromedriver.exe")

In [240]:
url= "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

In [239]:
driver.execute_script("window.scrollTo(0, 1000)")

In [245]:
records=[]
for row in driver.find_elements(By.XPATH,"(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp=''
    for element in row.find_elements(By.XPATH,".//td"):        
        temp+=element.text+'|'
    records.append(temp.split('|')[:-2])

df=pd.DataFrame(records, columns=['Rank', 'Video_Name', 'Artist_Name', 'Views_in_Billions', 'Upload_Date'])
arranged_cols=['Rank', 'Video_Name', 'Artist_Name', 'Upload_Date', 'Views_in_Billions']
df.Video_Name=df.Video_Name.apply(lambda x:x[:-4].strip('"'))
df=df[arranged_cols]
df

,Rank,Video_Name,Artist_Name,Upload_Date,Views_in_Billions
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.00
1,2.,Despacito,Luis Fonsi,"January 12, 2017",8.05
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.57
3,4.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",5.89
4,5.,Shape of You,Ed Sheeran,"January 30, 2017",5.88
5,6.,See You Again,Wiz Khalifa,"April 6, 2015",5.74
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",5.08
7,8.,Uptown Funk,Mark Ronson,"November 19, 2014",4.79
8,9.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",4.77
9,10.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.76
10,11.,Gangnam Style,Psy,"July 15, 2012",4.64
11,12.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.52
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.18
13,14.,Sugar,Maroon 5,"January 14, 2015",3.80
14,15.,Roar,Katy Perry,"September 5, 2013",3.70
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.70
16,17.,Axel F,Crazy Frog,"June 16, 2009",3.67
17,18.,Sorry,Justin Bieber,"October 22, 2015",3.62
18,19.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.53
19,20.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.46
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.42
21,22.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.40
22,23.,Faded,Alan Walker,"December 3, 2015",3.38
23,24.,Let Her Go,Passenger,"July 25, 2012",3.36
24,25.,Girls Like You,Maroon 5,"May 31, 2018",3.35
25,26.,Perfect,Ed Sheeran,"November 9, 2017",3.33
26,27.,Bailando,Enrique Iglesias,"April 11, 2014",3.31
27,28.,Lean On,Major Lazer,"March 22, 2015",3.31
28,29.,Humpty the train on a fruits ride,Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.26
29,30.,Lakdi Ki Kathi,Jingle Toons,"June 14, 2018",3.24